---
title: "Analysis"
author: "Adam Czepielik"
date: "October 24, 2018"
output: html_document
---

```{r}
library(ggplot2)
library(Polychrome)

theme_set(theme_minimal())
kelly <- kelly.colors(19)[2:19]
```


```{r}
data <- readr::read_csv("24urenloop.csv")

names(kelly) <- tail(data$name, 18)
```

```{r}
library(dplyr)

data %>% group_by(tstamp) %>% mutate(ord = order(laps + position, decreasing = TRUE)) %>% ungroup() %>% 
  ggplot(aes(tstamp, rev(ord), color = name)) + geom_path(size = 6) + 
  scale_color_manual(name = "", values = kelly, breaks = names(kelly)) +
  scale_y_continuous(breaks = 1:18, labels = 18:1) + 
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M") + 
  labs(title = "Changes of positions") + 
  theme(panel.grid = element_blank(), 
        axis.text.y = element_text(size = 11), 
        axis.text.x = element_text(size = 9),
        axis.title = element_blank())
```

```{r}
data %>% 
ggplot(aes(tstamp, laps + position, color = name)) + geom_line() + 
  scale_color_manual(values = kelly, breaks = names(kelly)) +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M")
```



```{r}
library(tidyr)

ahead <- function(team1, team2){
  data %>% 
    filter(name %in% c(team1, team2)) %>% 
    select(tstamp, name, laps, position) %>% 
    transmute(tstamp, name = factor(name, levels = c(team1, team2)), result = laps + position) %>% 
    unique() %>% spread(name, result) %>% 
    transmute(tstamp, difference = .[[2]] - .[[3]]) %>% 
    ggplot(aes(tstamp, difference)) + geom_line(aes(color = ifelse(difference > 0, team1, team2)), size = 1) + 
    geom_hline(aes(yintercept = 0), size = 1) + labs(title = paste(team1, "vs.", team2)) + scale_color_manual(name = "Adventage", values = kelly)
}

ahead("Apolloon", "VTK")
ahead("LBK", "Viva Ekonomika")
ahead("Medica", "Industria")
```

```{r}
#because of relatively rare sampling frequency speed variable might be biased. Here I calculate speed as a slope of distance ~ time (in m/s)

data <- data %>% unique() %>% group_by(name) %>% 
  mutate(dspeed = 550*((laps + position) - lag(laps + position))/as.numeric(tstamp - lag(tstamp))) %>% 
  filter(!is.nan(dspeed)) %>% ungroup()

library(forecast); library(tidyr)
speed <- function(teams){
  data %>% filter(name %in% teams) %>% select(tstamp, name, dspeed) %>%
    #spread(name, dspeed) %>% mutate_at(vars(-1), ma, order = 120) %>% gather(name, dspeed, -tstamp) %>% 
    ggplot(aes(tstamp, dspeed, color = name)) + 
    #geom_line(size = 1) +
    geom_smooth(method = "loess", se = FALSE, span = 0.15, method.args = list(degree = 0)) + 
    scale_color_manual(name = "Adventage", values = kelly)
}
```

```{r}
speed(c("VTK", "Apolloon"))
speed(c("LBK", "Viva Ekonomika"))
speed(c("Medica", "Industria"))
speed(unique(data$name))
```

